config/routes.rb
Shindig::Application.routes.draw do
  require 'resque/server'
  mount Resque::Server.new, :at => "/resque"
  namespace :api do
    namespace :v1 do
      resources :events do
        resources :tweets
        resources :menus
        resources :items
        resources :attendees do
          collection do
            get "current"
          end
        end
        resources :messages
        resources :possible_times
        resources :users do
          collection do
            get 'current'
          end
        end
        resources :possible_attendees
      end
      resources :restaraunts do
        collection do
          get "search"
        end
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :events, only: [:show, :create] do
    resources :attendees, only: [:new] do
      collection do
        get 'create_attendee'
      end
    end
  end
  root :to => "home#index"
end

app/views/layouts/_continue.html.slim
.row style="margin-top:20px;"
  a.continue.pull-right.btn.btn-primary.btn-large href="#"
    | Continue
    i.icon-play.icon-white

app/views/layouts/_flash_message.html.slim
- flash.each do |key, value|
  .alert.alert-info
    strong= value

app/views/layouts/_navbar.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      a.brand= image_tag "shindigwithme-logo.png"
      .nav-collapse
        ul.nav.pull-right
          li(style="line-height:30px")
            - if current_user
              a= "signed in as: #{current_user.username}"
            - else
            	a(href="/users/auth/facebook" class='btn btn-info')  Log in
          - if current_user
            li(style="line-height:30px")
              a(data-toggle="modal" href="#allEvents") Show Events

app/views/layouts/application.html.slim
doctype html
html
  head
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application", "http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"
    = airbrake_javascript_notifier
    = pusher_meta_tags
    = csrf_meta_tags
    title Shindig

  head
    = render "layouts/navbar"
    .container#main_content
      = render "layouts/flash_message"
      = yield

- if current_user
  #allEvents.modal.hide
    .modal-header
      button.close data-dismiss="modal" type="button"
      h3 Your Events
    .modal-body
      - current_user.attendees.includes(:event).each do |a|
        h4= link_to a.event.name, event_path(a.event.id)
    .modal-footer
      a.btn data-dismiss="modal" href="#" Close